#pragma once

enum class GameRuleIds {
  CommandBlockOutput     = 0,
  DoDaylightCycle        = 1,
  DoEntityDrops          = 2,
  DoFireTick             = 3,
  DoMobLoot              = 4,
  DoMobSpawning          = 5,
  DoTileDrops            = 6,
  DoWeatherCycle         = 7,
  DrowningDamage         = 8,
  FallDamage             = 9,
  FireDamage             = 10,
  KeepInventory          = 11,
  MobGriefing            = 12,
  Pvp                    = 13,
  ShowCoordinates        = 14,
  NaturalRegeneration    = 15,
  TntExplodes            = 16,
  SendCommandFeedback    = 17,
  MaxCommandChainLength  = 18,
  DoInsomnia             = 19,
  CommandBlocksEnabled   = 20,
  RandomTickSpeed        = 21,
  DoImmediateRespawn     = 22,
  ShowDeathMessages      = 23,
  FunctionCommandLimit   = 24,
  SpawnRadius            = 25,
  ShowTags               = 26
};